plugins:
  discourse_another_email_enabled:
    default: false
  discourse_another_email_smtp_authentication_mode: 
    default: "plain"
  discourse_another_email_smtp_address:
    default: "172.17.0.1"
  discourse_another_email_smtp_port:
    default: 587
    min: 0
    max: 65537
  discourse_another_email_smtp_username:
    default: "username@example.com"
  discourse_another_email_smtp_password:
    default: "password"
    secret: true
  discourse_another_email_force_from_domain:
    default: ""
    description: "Force all from addresses to use this domain (e.g., example.com). Leave empty to disable."
  discourse_another_email_force_smtp_username_to_sender:
    default: false
    description: "Force SMTP username to match the sender address"
  
